名称：构建 huggingface 图像

在：
  推:
    分支：[ 拥抱 ]
    路径：
      - 'Dockerfile'
      - 'index.js'
      - 'package.json'
      - 'index.html'
  拉取请求:
    分支：[ 拥抱 ]
  工作流触发:

工作：
  构建：
    运行于：ubuntu-latest
    权限：
      目录：
阅读
      套件： 写

    步骤：
      - 名称: 检出仓库
        使用：actions/checkout@v4
        与：
          参考： 拥抱

      - 名称: 登录 GitHub 容器注册表
        使用：docker/login-action@v3
        与：
          注册表：ghcr.io
          用户名：${{ github.演员 }}
          密码：${{ secrets.GITHUB_TOKEN }}

      - 名称: 设置Docker Buildx
        使用：docker/setup-buildx-action@v3

      - 名称: 构建并推送Docker镜像
        使用：docker/build-push-action@v5
        与：
          上下文：.
          推： 真
          标签： |
            ghcr.io/${{ github.repository_owner }}/welinzs:最新
          标签： |
            org.opencontainers.image.source=https://github.com/${{ github.仓库 }}
            org.opencontainers.image.description=http 服务器
            org.opencontainers.image.licenses=MIT
          缓存来源：类型=gha
          缓存到： 类型=gha，模式=max
